zavoca_core_controllers:
    resource: ../../zavoca/CoreBundle/src/Controller/
    type: annotation

controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
